name: 🚜 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build-and-test:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '2.1.2'

    - name: Cache Poetry virtualenv
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ runner.os }}-

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Build the package
      run: poetry build

#    - name: Run tests
#      run: |
#        poetry run pytest
